version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/javascript-game
    
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test-run
          command: npm run test
      #- run:
      #    name: docker-login
      #    command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #- run:
       #   name: build-docker-image
        #  command: docker build -t $IMAGE_NAME:latest .
      #- run:
       #   name: publish-docker-image
        #  command: docker push $IMAGE_NAME
      #- run: 
       #   name: set-environment-varibles
        #  command: echo $SERVER > server.crt && echo $PRIVATE_KEY > privatekey.pem
      #- run: 
       #   name: build-docker-image-for-integration-environment
        #  command: docker create -p 8443:8443 --name javascript-game $IMAGE_NAME
      #- run:
       #   name: copy-server-cert-and-private-key-accross
        #  command: docker cp ./privatekey.pem javascript-game:/privatekey.pem; docker cp ./server.crt javascript-game:/server.crt
     # - run: 
      #    name: start-docker-container
       #   command: docker start javascript-game
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\";export IMAGE_NAME=\"$IMAGE_NAME\";export SERVER=\"$SERVER\";export PRIVATE_KEY=\"$PRIVATE_KEY\";rm -rf javascript-game;git clone https://github.com/COLINSGITREPO/javascript-game.git;source javascript-game/deploy.sh"
